apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z7l3kup9f-dotnet-basic
  janus-idp.io/tekton: z7l3kup9f-dotnet-basic
  backstage.io/kubernetes-id: z7l3kup9f-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z7l3kup9f-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
